server:
  port: ${PORT:5000}

spring:
  datasource:
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/master.yaml
  #  jpa:
#    generate-ddl: true
#    show-sql: true
#    hibernate:
#      ddl-auto: create
  mail:
    host: smtp.gmail.com
    port: 587
    username: newsfeedinfoteam@gmail.com
    password: News12345
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true



news:
  api:
    url: http://newsapi.org/v2/top-headlines?sources=techcrunch&apiKey=1f82f278e4784d88b3455ebf6685ce8d



    #email configuration for application.properties

    #  spring.mail.host=smtp.gmail.com
    #  spring.mail.port=587
    #  spring.mail.username=<login user to smtp server>
    #  spring.mail.password=<login password to smtp server>
    #  spring.mail.properties.mail.smtp.auth=true
    #  spring.mail.properties.mail.smtp.starttls.enable=true
